# SPDX-FileCopyrightText: 2025 Battelle Memorial Institute
# SPDX-License-Identifier: BSD-2-Clause
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.14.8
      hooks:
          # Run the linter.
          - id: ruff-check
            types_or: [python, pyi]
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
            types_or: [python, pyi]
    - repo: https://codeberg.org/fsfe/reuse-tool
      rev: v6.2.0
      hooks:
          - id: reuse-lint-file
