# SPDX-FileCopyrightText: 2025 Battelle Memorial Institute
# SPDX-License-Identifier: BSD-2-Clause
name: Pytest
permissions:
    contents: read

on:
    pull_request:
        branches:
            - main # This workflow will run for PRs targeting the main branch

jobs:
    pytest:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v6
              with:
                  version: "latest"

            - name: Install dependencies with uv
              run: |
                  uv sync --all-extras --frozen && uv pip install jax torch --torch-backend=cpu

            - name: Run core tests
              run: |
                  uv run pytest -m "not bq and not docs"
          
            - name: Run non-core tests
              run: |
                  uv run pytest -m "bq or docs"
